"""Integration tests for the ``detection`` CLI group.

Fixtures are deliberately tiny and written directly, rather than generated by
running the Phase 2 and Phase 3 pipelines: a CLI test should fail because the
CLI is wrong, not because a generator upstream changed its output. Every test
writes into ``tmp_path`` and nothing runs at development scale.

Two properties are swept continuously. **No command may print an identifier**
-- not an anchor, a detection or alert identifier, an entity-scope pseudonym,
or an absolute path -- and **ground truth may reach only ``evaluate``**, which
is enforced by the absence of a ``--labels`` option everywhere else.
"""

from __future__ import annotations

import json
import re
from datetime import timedelta
from pathlib import Path
from typing import Any

import pytest
from typer.testing import CliRunner, Result

from password_attack_detector.cli import app
from password_attack_detector.detection.alerts import AlertBuilder
from password_attack_detector.detection.config import DetectionConfig
from password_attack_detector.detection.engine import DetectionEngine
from password_attack_detector.detection.schemas import EntityScopeRecord
from password_attack_detector.detection.scoring import RiskScorer
from password_attack_detector.detection.serialization import (
    ALERTS_FILE,
    DETECTIONS_FILE,
    EVALUATION_JSON_FILE,
    EVALUATION_MD_FILE,
    MANIFEST_FILE,
    QUALITY_JSON_FILE,
    QUALITY_MD_FILE,
    RISK_FILE,
    write_alerts,
    write_entity_scope,
    write_fired_detections,
    write_risk_assessments,
)
from tests.unit.detection import factories

runner = CliRunner()

_PSEUDONYM_RE = re.compile(r"\b(?:u|s|d|sess):[0-9a-f]{32}\b")
_UUID_RE = re.compile(
    r"\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\b"
)

#: The four scenario builders the snapshot fixture rotates through.
_BUILDERS = (
    factories.brute_force_row,
    factories.spraying_row,
    factories.stuffing_row,
    factories.quiet_row,
)

#: Anchors are UUID-shaped on purpose: a summary that leaked one would be
#: caught by the identifier sweep rather than passing unnoticed.
_ANCHOR_TEMPLATE = "3f2504e0-4f89-41d3-9a0c-0305e82c33{:02d}"


def invoke(*args: str) -> Result:
    """Run the CLI and return its result."""
    return runner.invoke(app, list(args))


def write_snapshots(
    path: Path, *, count: int = 12, overrides: dict[str, Any] | None = None
) -> list[str]:
    """Write a tiny feature-snapshot table and return its anchors."""
    import pyarrow as pa
    import pyarrow.parquet as pq

    catalog = factories.feature_catalog()
    anchors = [_ANCHOR_TEMPLATE.format(index) for index in range(count)]
    rows = [
        {
            **_BUILDERS[index % len(_BUILDERS)](
                catalog,
                anchor_event_id=anchors[index],
                anchor_event_time=factories.WHEN + timedelta(minutes=index * 3),
            ),
            **(overrides or {}),
        }
        for index in range(count)
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(pa.Table.from_pylist(rows), path)
    return anchors


def write_feature_manifest(path: Path, *, schema_version: str = "1.0.0") -> None:
    """Write a minimal source feature manifest."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(
            {
                "feature_schema_version": schema_version,
                "content_fingerprint": "a" * 64,
            }
        ),
        encoding="utf-8",
    )


def write_ground_truth(
    labels_path: Path, splits_path: Path, anchors: list[str]
) -> None:
    """Write Phase 3-shaped label and split tables for the fixture anchors."""
    import pyarrow as pa
    import pyarrow.parquet as pq

    scenarios = ("brute_force", "password_spraying", "credential_stuffing", "normal")
    splits = ("train", "validation", "test", "novel_anomaly_holdout")
    labels_path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(
        pa.Table.from_pylist(
            [
                {
                    "event_id": anchor,
                    "attack_class": scenarios[index % 4],
                    "malicious": index % 4 != 3,
                    "supervised_training_eligible": index % 4 != 3,
                }
                for index, anchor in enumerate(anchors)
            ]
        ),
        labels_path,
    )
    pq.write_table(
        pa.Table.from_pylist(
            [
                {
                    "event_id": anchor,
                    "split": splits[index % 4],
                    "exclusion_reason": None,
                }
                for index, anchor in enumerate(anchors)
            ]
        ),
        splits_path,
    )


def write_campaigns(path: Path, anchors: list[str]) -> None:
    """Write a Phase 2-shaped campaign table."""
    import pyarrow as pa
    import pyarrow.parquet as pq

    pq.write_table(
        pa.Table.from_pylist(
            [
                {"event_id": anchor, "campaign_id": f"campaign-{index % 3:04d}"}
                for index, anchor in enumerate(anchors)
                if index % 4 != 3
            ]
        ),
        path,
    )


def build_artifacts(directory: Path, *, scope: bool = False) -> dict[str, Any]:
    """Produce a published-shaped artifact set directly, bypassing the CLI."""
    catalog = factories.feature_catalog()
    config = DetectionConfig()
    engine = DetectionEngine(config, feature_catalog=catalog)
    anchors = [_ANCHOR_TEMPLATE.format(index) for index in range(12)]
    rows = [
        _BUILDERS[index % len(_BUILDERS)](
            catalog,
            anchor_event_id=anchors[index],
            anchor_event_time=factories.WHEN + timedelta(minutes=index * 3),
        )
        for index in range(12)
    ]
    detections = list(engine.run(rows).fired_detections)
    scored = RiskScorer(config).score(engine.run_diagnostic(rows))
    table = None
    if scope:
        from password_attack_detector.detection.alerts import build_entity_scope_table

        table = build_entity_scope_table(
            [
                EntityScopeRecord(
                    anchor_event_id=anchor,
                    user_scope=f"u:{index:032x}",
                    source_scope=f"s:{index % 2:032x}",
                )
                for index, anchor in enumerate(anchors)
            ]
        )
    alerting = AlertBuilder(config).build(
        scored.assessments, detections=detections, entity_scope=table
    )

    directory.mkdir(parents=True, exist_ok=True)
    write_fired_detections(detections, directory / DETECTIONS_FILE)
    write_risk_assessments(list(scored.assessments), directory / RISK_FILE)
    write_alerts(list(alerting.alerts), directory / ALERTS_FILE)
    return {
        "anchors": anchors,
        "detections": detections,
        "assessments": list(scored.assessments),
        "alerts": list(alerting.alerts),
    }


def assert_sanitized(result: Result, *secrets: str) -> None:
    """Assert no identifier, pseudonym, or absolute path reached the output."""
    output = result.output
    assert not _UUID_RE.search(output), output
    assert not _PSEUDONYM_RE.search(output), output
    assert "/home/" not in output
    for secret in secrets:
        assert secret not in output


# ---------------------------------------------------------------------------
# Help and wiring
# ---------------------------------------------------------------------------


def test_the_detection_group_is_wired_into_the_root_application() -> None:
    result = invoke("--help")
    assert result.exit_code == 0
    for group in ("data", "features", "detection"):
        assert group in result.output


@pytest.mark.parametrize("command", ["version", "doctor", "show-config"])
def test_the_existing_root_commands_still_work(command: str) -> None:
    """Adding a group must not disturb what was already there."""
    assert invoke(command, "--help").exit_code == 0


def test_detection_help_lists_every_command() -> None:
    result = invoke("detection", "--help")
    assert result.exit_code == 0
    for command in (
        "run",
        "validate",
        "profile",
        "evaluate",
        "verify-manifest",
        "catalog",
    ):
        assert command in result.output


@pytest.mark.parametrize(
    "command", ["run", "validate", "profile", "evaluate", "verify-manifest", "catalog"]
)
def test_every_subcommand_has_help(command: str) -> None:
    result = invoke("detection", command, "--help")
    assert result.exit_code == 0


def declared_options(command: str) -> set[str]:
    """Return the option flags a subcommand actually declares.

    Read from the click command rather than from rendered help text: the help
    for ``run`` explains in prose that it has no ``--labels`` option, and a
    substring scan would flag that sentence as the very thing it denies.
    """
    import typer.main

    # The objects below are click internals reached through Typer. click ships
    # no type stubs in this environment, so they are annotated Any rather than
    # imported for a type that mypy cannot resolve.
    click_app: Any = typer.main.get_command(app)
    group: Any = click_app.commands["detection"]
    target: Any = group.commands[command]
    flags: set[str] = set()
    for parameter in target.params:
        flags.update(getattr(parameter, "opts", ()))
    return flags


def test_run_declares_no_labels_or_splits_option() -> None:
    """The absence is the enforcement: ground truth cannot reach the engine."""
    flags = declared_options("run")
    assert "--labels" not in flags
    assert "--splits" not in flags
    assert not any("campaign" in flag for flag in flags)


def test_evaluate_is_the_only_command_declaring_labels() -> None:
    for command in ("run", "validate", "profile", "verify-manifest", "catalog"):
        assert "--labels" not in declared_options(command), command
        assert "--splits" not in declared_options(command), command
    assert "--labels" in declared_options("evaluate")
    assert "--splits" in declared_options("evaluate")


def test_only_run_and_validate_declare_an_entity_scope() -> None:
    """Scope reaches alert construction and its validator, and nothing else."""
    for command in ("profile", "evaluate", "catalog", "verify-manifest"):
        assert "--entity-scope" not in declared_options(command), command
    assert "--entity-scope" in declared_options("run")
    assert "--entity-scope" in declared_options("validate")


# ---------------------------------------------------------------------------
# catalog
# ---------------------------------------------------------------------------


def test_catalog_renders_every_registered_rule() -> None:
    from password_attack_detector.detection.catalog import RULE_CATALOG

    result = invoke("detection", "catalog")
    assert result.exit_code == 0
    for rule_id in RULE_CATALOG.rule_ids:
        assert rule_id in result.output


def test_catalog_shows_the_declared_contract() -> None:
    result = invoke("detection", "catalog")
    assert "Required features" in result.output
    assert "Thresholds" in result.output
    assert "Evidence codes" in result.output
    assert "Limitation" in result.output
    assert "min_pair_failures" in result.output
    assert "BF_PAIR_FAILURE_COUNT" in result.output


def test_catalog_markdown_shows_every_correlation_group() -> None:
    """Checked in Markdown: the text table truncates long group names."""
    from password_attack_detector.detection.enums import CorrelationGroup

    result = invoke("detection", "catalog", "--format", "markdown")
    assert result.exit_code == 0
    rendered = " ".join(result.output.split())
    for group in CorrelationGroup:
        assert str(group) in rendered


def test_catalog_renders_markdown(tmp_path: Path) -> None:
    destination = tmp_path / "rule-catalog.md"
    result = invoke(
        "detection", "catalog", "--format", "markdown", "--output", str(destination)
    )
    assert result.exit_code == 0
    rendered = destination.read_text(encoding="utf-8")
    assert rendered.startswith("# Rule Catalog")
    assert "PAD-BF-001" in rendered


def test_catalog_emits_no_executable_configuration() -> None:
    """Metadata only: no YAML a reader could mistake for runnable input."""
    output = invoke("detection", "catalog").output
    for marker in ("import ", "def ", "eval(", "exec(", "!!python"):
        assert marker not in output


def test_an_unknown_catalog_format_is_refused() -> None:
    result = invoke("detection", "catalog", "--format", "yaml")
    assert result.exit_code == 1


# ---------------------------------------------------------------------------
# run
# ---------------------------------------------------------------------------


def test_run_publishes_every_artifact(tmp_path: Path) -> None:
    features = tmp_path / "features" / "feature_snapshots.parquet"
    anchors = write_snapshots(features)
    manifest = tmp_path / "features" / "feature_manifest.json"
    write_feature_manifest(manifest)
    output = tmp_path / "detection"

    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--feature-manifest",
        str(manifest),
        "--output-dir",
        str(output),
    )
    assert result.exit_code == 0, result.output

    written = {path.name for path in output.iterdir()}
    assert written == {
        DETECTIONS_FILE,
        RISK_FILE,
        ALERTS_FILE,
        QUALITY_JSON_FILE,
        QUALITY_MD_FILE,
        MANIFEST_FILE,
    }
    assert_sanitized(result, *anchors)


def test_the_run_summary_reports_safe_aggregates(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--output-dir",
        str(tmp_path / "detection"),
    )
    assert result.exit_code == 0
    for heading in (
        "Evaluated snapshots",
        "Fired detections",
        "Risk assessments",
        "Insufficient data",
        "Alerts",
        "Grouping mode",
        "Validation",
    ):
        assert heading in result.output
    assert "category_scoped" in result.output


def test_a_run_with_nothing_firing_still_publishes(tmp_path: Path) -> None:
    """A quiet interval is an ordinary state, not a failure."""
    import pyarrow as pa
    import pyarrow.parquet as pq

    catalog = factories.feature_catalog()
    features = tmp_path / "feature_snapshots.parquet"
    rows = [
        factories.quiet_row(
            catalog,
            anchor_event_id=_ANCHOR_TEMPLATE.format(index),
            anchor_event_time=factories.WHEN + timedelta(minutes=index),
        )
        for index in range(4)
    ]
    pq.write_table(pa.Table.from_pylist(rows), features)

    output = tmp_path / "detection"
    result = invoke(
        "detection", "run", "--features", str(features), "--output-dir", str(output)
    )
    assert result.exit_code == 0, result.output
    assert (output / MANIFEST_FILE).exists()

    from password_attack_detector.detection.serialization import read_fired_detections

    assert read_fired_detections(output / DETECTIONS_FILE) == ()


def test_an_empty_feature_table_is_refused(tmp_path: Path) -> None:
    import pyarrow as pa
    import pyarrow.parquet as pq

    catalog = factories.feature_catalog()
    features = tmp_path / "feature_snapshots.parquet"
    empty = pa.Table.from_pylist([factories.quiet_row(catalog)]).slice(0, 0)
    pq.write_table(empty, features)

    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--output-dir",
        str(tmp_path / "detection"),
    )
    assert result.exit_code == 1
    assert "empty" in result.output


def test_a_missing_feature_table_is_refused(tmp_path: Path) -> None:
    result = invoke(
        "detection",
        "run",
        "--features",
        str(tmp_path / "absent.parquet"),
        "--output-dir",
        str(tmp_path / "detection"),
    )
    assert result.exit_code == 1
    assert "not found" in result.output


def test_an_incompatible_feature_schema_is_refused(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    manifest = tmp_path / "feature_manifest.json"
    write_feature_manifest(manifest, schema_version="9.9.9")

    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--feature-manifest",
        str(manifest),
        "--output-dir",
        str(tmp_path / "detection"),
    )
    assert result.exit_code == 1
    assert "incompatible" in result.output


@pytest.mark.parametrize(
    "column", ["label", "attack_class", "campaign_id", "split", "model_probability"]
)
def test_a_prohibited_feature_column_is_refused(tmp_path: Path, column: str) -> None:
    """Ground truth in the input aborts before any rule sees a row."""
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features, overrides={column: "poisoned"})

    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--output-dir",
        str(tmp_path / "detection"),
    )
    assert result.exit_code == 1
    assert "prohibited column" in result.output
    assert "poisoned" not in result.output


def test_run_refuses_to_overwrite_without_force(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    output = tmp_path / "detection"
    assert (
        invoke(
            "detection", "run", "--features", str(features), "--output-dir", str(output)
        ).exit_code
        == 0
    )

    result = invoke(
        "detection", "run", "--features", str(features), "--output-dir", str(output)
    )
    assert result.exit_code == 1
    assert "--force" in result.output


def test_run_replaces_when_force_is_given(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    output = tmp_path / "detection"
    invoke("detection", "run", "--features", str(features), "--output-dir", str(output))

    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--output-dir",
        str(output),
        "--force",
    )
    assert result.exit_code == 0, result.output
    assert (output / MANIFEST_FILE).exists()


def test_run_is_deterministic_across_two_directories(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    first, second = tmp_path / "one", tmp_path / "two"
    invoke("detection", "run", "--features", str(features), "--output-dir", str(first))
    invoke("detection", "run", "--features", str(features), "--output-dir", str(second))

    for name in (DETECTIONS_FILE, RISK_FILE, ALERTS_FILE):
        assert (first / name).read_bytes() == (second / name).read_bytes()
    left = json.loads((first / MANIFEST_FILE).read_text())
    right = json.loads((second / MANIFEST_FILE).read_text())
    assert left["content_fingerprint"] == right["content_fingerprint"]
    assert left["dataset_id"] == right["dataset_id"]


def write_marginal_snapshots(path: Path) -> list[str]:
    """Write snapshots that fire one rule at exactly its thresholds.

    Every saturating component contributes zero at exact equality, so the
    signal strength is the configured floor and the resulting risk lands in
    the LOW band -- the smallest finding the pipeline can produce.
    """
    import pyarrow as pa
    import pyarrow.parquet as pq

    catalog = factories.feature_catalog()
    anchors = [_ANCHOR_TEMPLATE.format(index) for index in range(4)]
    rows = [
        factories.bot_row(
            catalog,
            anchor_event_id=anchor,
            anchor_event_time=factories.WHEN + timedelta(hours=index * 4),
            source_attempt_count__15m=20,
            source_interarrival_coefficient_of_variation__15m=0.15,
            source_mean_interarrival_seconds__15m=120.0,
            source_unique_user_agent_count__1h=2,
        )
        for index, anchor in enumerate(anchors)
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    pq.write_table(pa.Table.from_pylist(rows), path)
    return anchors


def test_a_low_alert_is_emitted_when_the_floors_permit_it(tmp_path: Path) -> None:
    """LOW is an ordinary alert severity, reachable end to end."""
    import yaml

    from password_attack_detector.detection.serialization import read_alerts

    features = tmp_path / "feature_snapshots.parquet"
    write_marginal_snapshots(features)
    config = tmp_path / "rules.yaml"
    config.write_text(
        yaml.safe_dump(
            {
                "scoring": {"min_fired_risk_score": 1.0},
                "alerting": {"min_alert_risk_score": 1.0, "min_alert_severity": "low"},
            }
        ),
        encoding="utf-8",
    )
    output = tmp_path / "detection"
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--config",
        str(config),
        "--output-dir",
        str(output),
    )
    assert result.exit_code == 0, result.output

    alerts = read_alerts(output / ALERTS_FILE)
    assert any(str(alert.current_severity) == "low" for alert in alerts)


def test_a_raised_severity_floor_withholds_the_low_alert(tmp_path: Path) -> None:
    import yaml

    from password_attack_detector.detection.serialization import read_alerts

    features = tmp_path / "feature_snapshots.parquet"
    write_marginal_snapshots(features)
    config = tmp_path / "rules.yaml"
    config.write_text(
        yaml.safe_dump(
            {
                "scoring": {"min_fired_risk_score": 1.0},
                "alerting": {
                    "min_alert_risk_score": 1.0,
                    "min_alert_severity": "critical",
                },
            }
        ),
        encoding="utf-8",
    )
    output = tmp_path / "detection"
    assert (
        invoke(
            "detection",
            "run",
            "--features",
            str(features),
            "--config",
            str(config),
            "--output-dir",
            str(output),
        ).exit_code
        == 0
    )
    assert read_alerts(output / ALERTS_FILE) == ()


# ---------------------------------------------------------------------------
# run with entity scope
# ---------------------------------------------------------------------------


def test_an_entity_scoped_run_groups_on_the_scope(tmp_path: Path) -> None:
    from password_attack_detector.detection.serialization import read_alerts

    features = tmp_path / "feature_snapshots.parquet"
    anchors = write_snapshots(features)
    scope_path = tmp_path / "detection_entity_scope.parquet"
    write_entity_scope(
        [
            EntityScopeRecord(
                anchor_event_id=anchor,
                user_scope=f"u:{index:032x}",
                source_scope=f"s:{index % 2:032x}",
            )
            for index, anchor in enumerate(anchors)
        ],
        scope_path,
    )
    output = tmp_path / "detection"
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--entity-scope",
        str(scope_path),
        "--output-dir",
        str(output),
    )
    assert result.exit_code == 0, result.output
    assert "entity_scoped" in result.output

    alerts = read_alerts(output / ALERTS_FILE)
    assert any(alert.scope_value is not None for alert in alerts)
    assert_sanitized(result, *anchors)

    manifest = json.loads((output / MANIFEST_FILE).read_text())
    assert manifest["entity_scope_present"] is True
    assert manifest["alert_grouping_mode"] == "entity_scoped"


def test_no_scope_table_falls_back_to_category_grouping(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    output = tmp_path / "detection"
    result = invoke(
        "detection", "run", "--features", str(features), "--output-dir", str(output)
    )
    assert result.exit_code == 0
    assert "category_scoped" in result.output
    manifest = json.loads((output / MANIFEST_FILE).read_text())
    assert manifest["entity_scope_present"] is False
    assert manifest["alert_grouping_mode"] == "category_scoped"


def test_duplicate_scope_anchors_abort_the_run(tmp_path: Path) -> None:
    import pyarrow as pa
    import pyarrow.parquet as pq

    features = tmp_path / "feature_snapshots.parquet"
    anchors = write_snapshots(features)
    scope_path = tmp_path / "scope.parquet"
    pq.write_table(
        pa.Table.from_pylist(
            [
                {
                    "anchor_event_id": anchors[0],
                    "user_scope": "u:" + "a" * 32,
                    "source_scope": None,
                },
                {
                    "anchor_event_id": anchors[0],
                    "user_scope": "u:" + "b" * 32,
                    "source_scope": None,
                },
            ]
        ),
        scope_path,
    )
    output = tmp_path / "detection"
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--entity-scope",
        str(scope_path),
        "--output-dir",
        str(output),
    )
    assert result.exit_code == 1
    assert "duplicate" in result.output
    assert not output.exists() or list(output.iterdir()) == []
    assert_sanitized(result, *anchors)


def test_a_scope_relationship_mismatch_aborts_the_run(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    anchors = write_snapshots(features)
    scope_path = tmp_path / "scope.parquet"
    write_entity_scope(
        [
            EntityScopeRecord(anchor_event_id=anchors[0], user_scope="u:" + "a" * 32),
            EntityScopeRecord(
                anchor_event_id="unmatched-anchor", user_scope="u:" + "b" * 32
            ),
        ],
        scope_path,
    )
    output = tmp_path / "detection"
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--entity-scope",
        str(scope_path),
        "--output-dir",
        str(output),
    )
    assert result.exit_code == 1
    assert "does not match" in result.output
    assert "unmatched-anchor" not in result.output


def test_a_missing_scope_table_is_refused(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--entity-scope",
        str(tmp_path / "absent.parquet"),
        "--output-dir",
        str(tmp_path / "detection"),
    )
    assert result.exit_code == 1
    assert "not found" in result.output


# ---------------------------------------------------------------------------
# validate
# ---------------------------------------------------------------------------


def test_validate_passes_on_a_coherent_artifact_set(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    result = invoke(
        "detection",
        "validate",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
    )
    assert result.exit_code == 0, result.output
    assert "warning" in result.output or "valid" in result.output
    assert_sanitized(result, *built["anchors"])


def test_validate_fails_on_a_broken_relationship(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    trimmed = [
        item
        for item in built["assessments"]
        if item.anchor_event_id != built["detections"][0].anchor_event_id
    ]
    write_risk_assessments(trimmed, directory / RISK_FILE)

    result = invoke(
        "detection",
        "validate",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
    )
    assert result.exit_code == 1
    assert "D028" in result.output or "D029" in result.output
    assert_sanitized(result, *built["anchors"])


def test_validate_reports_codes_columns_and_counts(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    build_artifacts(directory)
    result = invoke(
        "detection",
        "validate",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
    )
    assert "Code" in result.output
    assert "Column" in result.output
    assert "Count" in result.output


def test_validate_refuses_a_missing_artifact(tmp_path: Path) -> None:
    result = invoke(
        "detection",
        "validate",
        str(tmp_path / "absent.parquet"),
        "--risk-assessments",
        str(tmp_path / "absent2.parquet"),
        "--alerts",
        str(tmp_path / "absent3.parquet"),
    )
    assert result.exit_code == 1
    assert "not found" in result.output


# ---------------------------------------------------------------------------
# profile
# ---------------------------------------------------------------------------


def test_profile_writes_both_report_formats(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    reports = tmp_path / "reports"

    result = invoke(
        "detection",
        "profile",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--output-dir",
        str(reports),
    )
    assert result.exit_code == 0, result.output
    assert (reports / QUALITY_JSON_FILE).exists()
    assert (reports / QUALITY_MD_FILE).exists()
    assert_sanitized(result, *built["anchors"])


def test_profile_states_what_its_numbers_mean(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    build_artifacts(directory)
    reports = tmp_path / "reports"
    result = invoke(
        "detection",
        "profile",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--output-dir",
        str(reports),
    )
    assert "not a probability" in result.output

    payload = json.loads((reports / QUALITY_JSON_FILE).read_text())
    definitions = payload["definitions"]
    assert "not a probability" in definitions["risk_score"].lower()
    assert "not a probability" in definitions["signal_strength"].lower()
    assert "arithmetic mean" in definitions["aggregate_risk_score"].lower()
    assert "maximum" in definitions["peak_risk_score"].lower()
    assert "not causal proof" in definitions["evidence"].lower()


def test_profile_reports_carry_no_identifier(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory, scope=True)
    reports = tmp_path / "reports"
    invoke(
        "detection",
        "profile",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--output-dir",
        str(reports),
    )
    for name in (QUALITY_JSON_FILE, QUALITY_MD_FILE):
        rendered = (reports / name).read_text()
        assert not _UUID_RE.search(rendered)
        assert not _PSEUDONYM_RE.search(rendered)
        assert "/home/" not in rendered
        for anchor in built["anchors"]:
            assert anchor not in rendered


# ---------------------------------------------------------------------------
# evaluate
# ---------------------------------------------------------------------------


def test_evaluate_writes_both_report_formats(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    labels = tmp_path / "feature_labels.parquet"
    splits = tmp_path / "feature_splits.parquet"
    write_ground_truth(labels, splits, built["anchors"])
    reports = tmp_path / "reports"

    result = invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(labels),
        "--splits",
        str(splits),
        "--output-dir",
        str(reports),
    )
    assert result.exit_code == 0, result.output
    assert (reports / EVALUATION_JSON_FILE).exists()
    assert (reports / EVALUATION_MD_FILE).exists()
    assert_sanitized(result, *built["anchors"])


def test_evaluate_labels_its_output_synthetic(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    labels = tmp_path / "feature_labels.parquet"
    splits = tmp_path / "feature_splits.parquet"
    write_ground_truth(labels, splits, built["anchors"])
    reports = tmp_path / "reports"

    result = invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(labels),
        "--splits",
        str(splits),
        "--output-dir",
        str(reports),
    )
    # Rich wraps the caveat across lines, so whitespace is normalised first.
    flowed = " ".join(result.output.lower().split())
    assert "synthetic" in flowed
    assert "not evidence of real-world detection effectiveness" in flowed

    payload = json.loads((reports / EVALUATION_JSON_FILE).read_text())
    assert payload["threshold_optimization_performed"] is False
    assert "synthetic" in payload["synthetic_caveat"].lower()


def test_evaluate_separates_the_splits_and_the_holdout(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    labels = tmp_path / "feature_labels.parquet"
    splits = tmp_path / "feature_splits.parquet"
    write_ground_truth(labels, splits, built["anchors"])
    reports = tmp_path / "reports"

    result = invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(labels),
        "--splits",
        str(splits),
        "--output-dir",
        str(reports),
    )
    assert "holdout reported separately" in result.output

    payload = json.loads((reports / EVALUATION_JSON_FILE).read_text())
    assert sorted(payload["by_split"]) == ["test", "train", "validation"]
    assert payload["novel_holdout"] is not None
    assert payload["novel_holdout"]["split"] == "novel_anomaly_holdout"


def test_evaluate_reports_campaign_metrics_when_supplied(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    labels = tmp_path / "feature_labels.parquet"
    splits = tmp_path / "feature_splits.parquet"
    campaigns = tmp_path / "labels.parquet"
    write_ground_truth(labels, splits, built["anchors"])
    write_campaigns(campaigns, built["anchors"])
    reports = tmp_path / "reports"

    invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(labels),
        "--splits",
        str(splits),
        "--campaign-labels",
        str(campaigns),
        "--output-dir",
        str(reports),
    )
    payload = json.loads((reports / EVALUATION_JSON_FILE).read_text())
    assert payload["campaign_metrics"]["available"] is True
    assert payload["campaign_metrics"]["campaign_count"] > 0


def test_evaluate_reports_campaigns_unavailable_without_the_table(
    tmp_path: Path,
) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    labels = tmp_path / "feature_labels.parquet"
    splits = tmp_path / "feature_splits.parquet"
    write_ground_truth(labels, splits, built["anchors"])
    reports = tmp_path / "reports"

    invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(labels),
        "--splits",
        str(splits),
        "--output-dir",
        str(reports),
    )
    payload = json.loads((reports / EVALUATION_JSON_FILE).read_text())
    assert payload["campaign_metrics"]["available"] is False
    assert payload["campaign_metrics"]["coverage"] is None


def test_evaluation_reports_carry_no_identifier(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    labels = tmp_path / "feature_labels.parquet"
    splits = tmp_path / "feature_splits.parquet"
    campaigns = tmp_path / "labels.parquet"
    write_ground_truth(labels, splits, built["anchors"])
    write_campaigns(campaigns, built["anchors"])
    reports = tmp_path / "reports"

    invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(labels),
        "--splits",
        str(splits),
        "--campaign-labels",
        str(campaigns),
        "--output-dir",
        str(reports),
    )
    for name in (EVALUATION_JSON_FILE, EVALUATION_MD_FILE):
        rendered = (reports / name).read_text()
        assert not _UUID_RE.search(rendered)
        assert not _PSEUDONYM_RE.search(rendered)
        assert "campaign-0000" not in rendered
        assert "/home/" not in rendered


def test_evaluate_refuses_a_missing_label_table(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    build_artifacts(directory)
    result = invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(tmp_path / "absent.parquet"),
        "--splits",
        str(tmp_path / "absent2.parquet"),
    )
    assert result.exit_code == 1
    assert "not found" in result.output


# ---------------------------------------------------------------------------
# verify-manifest
# ---------------------------------------------------------------------------


def published(tmp_path: Path, **overrides: str) -> tuple[Path, list[str]]:
    """Publish an artifact set through the CLI and return its directory."""
    features = tmp_path / "feature_snapshots.parquet"
    anchors = write_snapshots(features)
    output = tmp_path / "detection"
    args = [
        "detection",
        "run",
        "--features",
        str(features),
        "--output-dir",
        str(output),
    ]
    for name, value in overrides.items():
        args.extend([f"--{name.replace('_', '-')}", value])
    result = invoke(*args)
    assert result.exit_code == 0, result.output
    return output, anchors


def test_verify_manifest_passes_on_a_published_set(tmp_path: Path) -> None:
    directory, anchors = published(tmp_path)
    result = invoke("detection", "verify-manifest", str(directory))
    assert result.exit_code == 0, result.output
    assert "FAIL" not in result.output
    assert_sanitized(result, *anchors)


def test_verify_manifest_accepts_the_manifest_path_itself(tmp_path: Path) -> None:
    directory, _ = published(tmp_path)
    result = invoke("detection", "verify-manifest", str(directory / MANIFEST_FILE))
    assert result.exit_code == 0, result.output


def test_verify_manifest_fails_on_a_tampered_artifact(tmp_path: Path) -> None:
    directory, anchors = published(tmp_path)
    (directory / DETECTIONS_FILE).write_bytes(b"corrupted")
    result = invoke("detection", "verify-manifest", str(directory))
    assert result.exit_code == 1
    assert "FAIL" in result.output
    assert_sanitized(result, *anchors)


def test_verify_manifest_fails_on_a_missing_artifact(tmp_path: Path) -> None:
    directory, _ = published(tmp_path)
    (directory / ALERTS_FILE).unlink()
    assert invoke("detection", "verify-manifest", str(directory)).exit_code == 1


def test_verify_manifest_fails_on_a_traversal_path(tmp_path: Path) -> None:
    directory, _ = published(tmp_path)
    manifest_path = directory / MANIFEST_FILE
    raw = json.loads(manifest_path.read_text())
    raw["artifacts"][0]["relative_path"] = f"../{DETECTIONS_FILE}"
    manifest_path.write_text(json.dumps(raw, indent=2))
    result = invoke("detection", "verify-manifest", str(directory))
    assert result.exit_code == 1
    assert "ARTIFACT_PATHS_NO_DOTDOT" in result.output


def test_verify_manifest_fails_on_a_stale_configuration(tmp_path: Path) -> None:
    import yaml

    directory, _ = published(tmp_path)
    config = tmp_path / "retuned.yaml"
    config.write_text(
        yaml.safe_dump(
            {"rules": {"PAD-BF-001": {"parameters": {"min_pair_failures": 3}}}}
        ),
        encoding="utf-8",
    )
    result = invoke(
        "detection", "verify-manifest", str(directory), "--config", str(config)
    )
    assert result.exit_code == 1
    assert "CONFIG_FINGERPRINT_MATCH" in result.output


def test_verify_manifest_refuses_a_missing_directory(tmp_path: Path) -> None:
    result = invoke("detection", "verify-manifest", str(tmp_path / "absent"))
    assert result.exit_code == 1
    assert "not found" in result.output


# ---------------------------------------------------------------------------
# Entry points and isolation
# ---------------------------------------------------------------------------


def test_the_console_entry_point_exposes_the_group() -> None:
    import subprocess
    import sys

    completed = subprocess.run(
        [sys.executable, "-m", "password_attack_detector", "detection", "--help"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0
    assert "verify-manifest" in completed.stdout


def test_the_module_entry_point_runs_the_catalog() -> None:
    import subprocess
    import sys

    completed = subprocess.run(
        [sys.executable, "-m", "password_attack_detector", "detection", "catalog"],
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0
    assert "PAD-BF-001" in completed.stdout


def test_the_output_carries_no_ansi_escape_under_capture() -> None:
    """The inherited colour-isolation fixture must keep working."""
    result = invoke("detection", "catalog")
    assert "\x1b[" not in result.output


# ---------------------------------------------------------------------------
# Remaining paths
# ---------------------------------------------------------------------------


def test_an_unexpected_failure_is_reported_by_type_alone(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An internal message was not written with disclosure in mind."""

    def explode(*args: Any, **kwargs: Any) -> Any:
        raise RuntimeError("internal detail with /home/someone/secret in it")

    monkeypatch.setattr(
        "password_attack_detector.detection.serialization.read_feature_snapshot_rows",
        explode,
    )
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--output-dir",
        str(tmp_path / "detection"),
    )
    assert result.exit_code == 1
    assert "RuntimeError" in result.output
    assert "/home/" not in result.output
    assert "secret" not in result.output


def test_an_unreadable_feature_manifest_is_refused(tmp_path: Path) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    manifest = tmp_path / "feature_manifest.json"
    manifest.write_text("{ not json", encoding="utf-8")
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--feature-manifest",
        str(manifest),
        "--output-dir",
        str(tmp_path / "detection"),
    )
    assert result.exit_code == 1
    assert "Cannot read the feature manifest" in result.output


def test_catalog_text_mode_can_also_write_a_file(tmp_path: Path) -> None:
    destination = tmp_path / "catalog.md"
    result = invoke("detection", "catalog", "--output", str(destination))
    assert result.exit_code == 0
    assert destination.read_text(encoding="utf-8").startswith("# Rule Catalog")


def test_a_failed_validation_aborts_the_run_without_publishing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Nothing is published when the artifacts do not validate."""
    from password_attack_detector.detection.schemas import (
        DetectionValidationFinding,
        DetectionValidationResult,
        DetectionValidationStatus,
    )

    def invalid(self: Any, *args: Any, **kwargs: Any) -> DetectionValidationResult:
        return DetectionValidationResult(
            status=DetectionValidationStatus.INVALID,
            errors=(
                DetectionValidationFinding(
                    code="D005",
                    message="1 detection identifier(s) repeat",
                    column="detection_id",
                    count=1,
                ),
            ),
        )

    monkeypatch.setattr(
        "password_attack_detector.detection.validation.DetectionValidator.validate",
        invalid,
    )
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    output = tmp_path / "detection"
    result = invoke(
        "detection", "run", "--features", str(features), "--output-dir", str(output)
    )
    assert result.exit_code == 1
    assert "failed validation" in result.output
    assert "D005" in result.output
    assert not output.exists() or list(output.iterdir()) == []


def test_a_separate_reports_directory_also_receives_the_report(
    tmp_path: Path,
) -> None:
    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    output = tmp_path / "detection"
    reports = tmp_path / "reports"
    result = invoke(
        "detection",
        "run",
        "--features",
        str(features),
        "--output-dir",
        str(output),
        "--reports-dir",
        str(reports),
    )
    assert result.exit_code == 0, result.output
    assert (reports / QUALITY_JSON_FILE).exists()
    assert (reports / QUALITY_MD_FILE).exists()
    assert (output / QUALITY_JSON_FILE).exists()


def test_validate_reports_no_findings_when_there_are_none(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from password_attack_detector.detection.schemas import (
        DetectionValidationResult,
        DetectionValidationStatus,
    )

    def clean(self: Any, *args: Any, **kwargs: Any) -> DetectionValidationResult:
        return DetectionValidationResult(status=DetectionValidationStatus.VALID)

    monkeypatch.setattr(
        "password_attack_detector.detection.validation.DetectionValidator.validate",
        clean,
    )
    directory = tmp_path / "detection"
    build_artifacts(directory)
    result = invoke(
        "detection",
        "validate",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
    )
    assert result.exit_code == 0
    assert "No findings" in result.output


def test_profile_refuses_a_missing_artifact(tmp_path: Path) -> None:
    result = invoke(
        "detection",
        "profile",
        str(tmp_path / "absent.parquet"),
        "--risk-assessments",
        str(tmp_path / "absent2.parquet"),
        "--alerts",
        str(tmp_path / "absent3.parquet"),
    )
    assert result.exit_code == 1
    assert "not found" in result.output


def test_evaluate_refuses_a_missing_campaign_table(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    labels = tmp_path / "feature_labels.parquet"
    splits = tmp_path / "feature_splits.parquet"
    write_ground_truth(labels, splits, built["anchors"])
    result = invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(labels),
        "--splits",
        str(splits),
        "--campaign-labels",
        str(tmp_path / "absent.parquet"),
    )
    assert result.exit_code == 1
    assert "Campaign labels not found" in result.output


def test_evaluate_refuses_an_unreadable_label_table(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    build_artifacts(directory)
    labels = tmp_path / "feature_labels.parquet"
    labels.write_text("not parquet", encoding="utf-8")
    splits = tmp_path / "feature_splits.parquet"
    splits.write_text("not parquet", encoding="utf-8")
    result = invoke(
        "detection",
        "evaluate",
        "--detections",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--labels",
        str(labels),
        "--splits",
        str(splits),
    )
    assert result.exit_code == 1
    assert "Cannot read the label table" in result.output


# ---------------------------------------------------------------------------
# Profile reports unavailable, never a fabricated zero
# ---------------------------------------------------------------------------


def test_profile_reports_unavailable_rather_than_zero(tmp_path: Path) -> None:
    """A counter the published tables do not record must not read as zero."""
    from password_attack_detector.detection.quality import (
        RECONSTRUCTED_WARNING_CODE,
        UNAVAILABLE_LABEL,
        UNAVAILABLE_WHEN_RECONSTRUCTED,
    )

    directory = tmp_path / "detection"
    build_artifacts(directory)
    reports = tmp_path / "reports"
    result = invoke(
        "detection",
        "profile",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--output-dir",
        str(reports),
    )
    assert result.exit_code == 0, result.output

    payload = json.loads((reports / QUALITY_JSON_FILE).read_text())
    assert payload["report_source"] == "published_artifacts"
    for name in UNAVAILABLE_WHEN_RECONSTRUCTED:
        assert payload[name] is None, name

    markdown = (reports / QUALITY_MD_FILE).read_text()
    assert RECONSTRUCTED_WARNING_CODE in markdown
    assert f"| Not fired | {UNAVAILABLE_LABEL} |" in markdown
    assert f"| Suppressed total | {UNAVAILABLE_LABEL} |" in markdown


def test_profile_keeps_derivable_counts_exact(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    built = build_artifacts(directory)
    reports = tmp_path / "reports"
    invoke(
        "detection",
        "profile",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--output-dir",
        str(reports),
    )
    payload = json.loads((reports / QUALITY_JSON_FILE).read_text())
    assert payload["fired_count"] == len(built["detections"])
    assert payload["evaluated_snapshot_count"] == len(built["assessments"])
    assert payload["alert_count"] == len(built["alerts"])
    assert payload["insufficient_data_count"] == sum(
        item.insufficient_data_count for item in built["assessments"]
    )


def test_profile_explains_the_reconstruction_limitation(tmp_path: Path) -> None:
    directory = tmp_path / "detection"
    build_artifacts(directory)
    reports = tmp_path / "reports"
    result = invoke(
        "detection",
        "profile",
        str(directory / DETECTIONS_FILE),
        "--risk-assessments",
        str(directory / RISK_FILE),
        "--alerts",
        str(directory / ALERTS_FILE),
        "--output-dir",
        str(reports),
    )
    flowed = " ".join(result.output.split())
    assert "Q001" in flowed
    assert "reconstructed from published artifacts" in flowed
    assert "unavailable rather than zero" in flowed

    payload = json.loads((reports / QUALITY_JSON_FILE).read_text())
    assert "reconstructed from published artifacts" in payload["reconstruction_note"]


def test_a_run_report_stays_fully_populated(tmp_path: Path) -> None:
    """The live-run report keeps integer counts, including measured zeros."""
    from password_attack_detector.detection.quality import (
        UNAVAILABLE_WHEN_RECONSTRUCTED,
    )

    features = tmp_path / "feature_snapshots.parquet"
    write_snapshots(features)
    output = tmp_path / "detection"
    assert (
        invoke(
            "detection",
            "run",
            "--features",
            str(features),
            "--output-dir",
            str(output),
        ).exit_code
        == 0
    )

    payload = json.loads((output / QUALITY_JSON_FILE).read_text())
    assert payload["report_source"] == "live_run"
    assert payload["unavailable_metrics"] == []
    assert payload["reconstruction_note"] is None
    for name in UNAVAILABLE_WHEN_RECONSTRUCTED:
        assert isinstance(payload[name], int), name
    assert payload["suppressed_total"] == 0
