"""Canonical authentication event and ground-truth label schemas.

``AuthEvent`` is the canonical record written to Parquet and used for all
downstream analysis.  It must never contain ground-truth labels or features
derived from detection rules.

``GroundTruthLabel`` is the separate synthetic label table.  It may only be
joined to ``AuthEvent`` by ``event_id`` inside controlled training or
evaluation workflows.

Design guarantees
-----------------
- All identifier fields contain prefixed pseudonymous values only.
- ``event_time`` is always UTC-normalised.
- ``failure_reason`` is required (including ``FailureReason.UNKNOWN``) when
  ``authentication_outcome`` is ``FAILURE`` or ``BLOCKED``.
- Extra fields are forbidden (``extra="forbid"``).
- No ground-truth column may appear in ``AuthEvent`` (asserted by tests).
"""

from __future__ import annotations

import re
from datetime import UTC, datetime
from typing import Literal, Self
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    field_validator,
    model_validator,
)

from password_attack_detector.data.enums import (
    AuthMethod,
    AuthOutcome,
    CampaignStage,
    ClientType,
    FailureReason,
    MFAOutcome,
    ScenarioType,
)

__all__ = [
    "PROHIBITED_GT_COLUMNS",
    "SCHEMA_VERSION",
    "AuthEvent",
    "GroundTruthLabel",
]

# Current canonical schema version.  Increment when the field set changes in a
# backwards-incompatible way.
SCHEMA_VERSION: str = "1.0.0"

# Columns that must never appear in the canonical authentication-event table.
# Tests assert that this set is disjoint from ``AuthEvent.model_fields``.
PROHIBITED_GT_COLUMNS: frozenset[str] = frozenset(
    {
        "label",
        "target",
        "attack_label",
        "scenario",
        "campaign_id",
        "malicious",
        "risk_score",
        "attack_probability",
        "is_attack",
        "supervised_training_eligible",
    }
)

# Compiled patterns for field-level validation.
_PSEUDONYM_RE = re.compile(r"^(u|s|d|sess):[0-9a-f]{32}$")
_COUNTRY_CODE_RE = re.compile(r"^[A-Z]{2}$")

# FailureReason values that are valid when outcome is BLOCKED.
_BLOCKED_VALID_REASONS: frozenset[FailureReason] = frozenset(
    {
        FailureReason.IP_BLOCKED,
        FailureReason.RATE_LIMITED,
        FailureReason.SUSPICIOUS_ACTIVITY,
        FailureReason.ACCOUNT_LOCKED,
        FailureReason.ACCOUNT_DISABLED,
        FailureReason.UNKNOWN,
    }
)


class AuthEvent(BaseModel):
    """One canonical authentication event.

    All identifier fields (``user_id``, ``source_id``, ``device_id``,
    ``session_id``) must contain prefixed pseudonymous values generated by
    ``PseudonymService`` for real data or by the deterministic synthetic
    generator for synthetic data.

    No plaintext usernames, IP addresses, device fingerprints, session tokens,
    passwords, or hashes may appear in any field.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    schema_version: Literal["1.0.0"] = "1.0.0"
    event_id: UUID
    event_time: AwareDatetime
    user_id: str
    source_id: str
    device_id: str
    session_id: str
    application_id: str
    authentication_method: AuthMethod
    authentication_outcome: AuthOutcome
    failure_reason: FailureReason | None = None
    mfa_outcome: MFAOutcome | None = None
    country_code: str | None = None
    region_code: str | None = None
    coarse_latitude: float | None = None
    coarse_longitude: float | None = None
    user_agent_family: str | None = None
    operating_system_family: str | None = None
    client_type: ClientType | None = None
    response_time_ms: int | None = None

    # ------------------------------------------------------------------
    # Field-level validators
    # ------------------------------------------------------------------

    @field_validator("event_time", mode="after")
    @classmethod
    def normalize_to_utc(cls, v: datetime) -> datetime:
        """Normalise a timezone-aware datetime to UTC."""
        return v.astimezone(UTC)

    @field_validator("user_id", "source_id", "device_id", "session_id", mode="after")
    @classmethod
    def validate_pseudonym_format(cls, v: str) -> str:
        """Require prefixed pseudonym format: ``prefix:hex32``."""
        if not _PSEUDONYM_RE.match(v):
            raise ValueError(
                "Identifier must be a prefixed pseudonym matching "
                r"'^(u|s|d|sess):[0-9a-f]{32}$'"
            )
        return v

    @field_validator("country_code", mode="after")
    @classmethod
    def validate_country_code(cls, v: str | None) -> str | None:
        """Require ISO 3166-1 alpha-2 format when present."""
        if v is not None and not _COUNTRY_CODE_RE.match(v):
            raise ValueError(
                "country_code must be exactly 2 uppercase ASCII letters "
                "(ISO 3166-1 alpha-2)"
            )
        return v

    @field_validator("coarse_latitude", mode="after")
    @classmethod
    def validate_latitude(cls, v: float | None) -> float | None:
        """Require latitude in [-90.0, 90.0]."""
        if v is not None and not (-90.0 <= v <= 90.0):
            raise ValueError(f"coarse_latitude must be in [-90.0, 90.0], got {v}")
        return v

    @field_validator("coarse_longitude", mode="after")
    @classmethod
    def validate_longitude(cls, v: float | None) -> float | None:
        """Require longitude in [-180.0, 180.0]."""
        if v is not None and not (-180.0 <= v <= 180.0):
            raise ValueError(f"coarse_longitude must be in [-180.0, 180.0], got {v}")
        return v

    @field_validator("response_time_ms", mode="after")
    @classmethod
    def validate_response_time(cls, v: int | None) -> int | None:
        """Require response time in [0, 30 000] ms."""
        if v is not None and not (0 <= v <= 30_000):
            raise ValueError(f"response_time_ms must be in [0, 30000], got {v}")
        return v

    # ------------------------------------------------------------------
    # Cross-field validators
    # ------------------------------------------------------------------

    @model_validator(mode="after")
    def check_outcome_failure_reason(self) -> Self:
        """Enforce outcome/failure_reason consistency.

        - SUCCESS   → failure_reason must be None
        - FAILURE   → failure_reason must be a FailureReason value
        - BLOCKED   → failure_reason must be a blocking-valid FailureReason
        - CHALLENGED→ failure_reason must be None
        """
        outcome = self.authentication_outcome
        fr = self.failure_reason

        if outcome == AuthOutcome.SUCCESS and fr is not None:
            raise ValueError(
                "failure_reason must be None when authentication_outcome is SUCCESS"
            )
        if outcome == AuthOutcome.FAILURE and fr is None:
            raise ValueError(
                "failure_reason must be set when authentication_outcome is FAILURE; "
                "use FailureReason.UNKNOWN when the specific reason is unavailable"
            )
        if outcome == AuthOutcome.BLOCKED:
            if fr is None:
                raise ValueError(
                    "failure_reason must be set when authentication_outcome is BLOCKED"
                )
            if fr not in _BLOCKED_VALID_REASONS:
                valid = sorted(r.value for r in _BLOCKED_VALID_REASONS)
                raise ValueError(
                    f"failure_reason {fr.value!r} is not valid for BLOCKED outcome; "
                    f"valid values: {valid}"
                )
        if outcome == AuthOutcome.CHALLENGED and fr is not None:
            raise ValueError(
                "failure_reason must be None when authentication_outcome is CHALLENGED"
            )
        return self

    @model_validator(mode="after")
    def check_mfa_consistency(self) -> Self:
        """MFA_BYPASSED is only valid with SUCCESS or FAILURE outcomes."""
        if (
            self.mfa_outcome == MFAOutcome.BYPASSED
            and self.authentication_outcome
            not in {
                AuthOutcome.SUCCESS,
                AuthOutcome.FAILURE,
            }
        ):
            raise ValueError(
                "mfa_outcome BYPASSED is only valid when authentication_outcome "
                "is SUCCESS or FAILURE"
            )
        return self


class GroundTruthLabel(BaseModel):
    """Synthetic ground-truth label for one event.

    Must never be included in the canonical authentication-event Parquet file.
    May only be joined to ``AuthEvent`` by ``event_id`` inside controlled
    training or evaluation workflows.

    Uses typed generation metadata instead of a free-text notes field to keep
    ground truth machine-readable and reduce accidental leakage.
    """

    model_config = ConfigDict(extra="forbid", frozen=True)

    event_id: UUID
    campaign_id: str
    scenario: ScenarioType
    malicious: bool
    supervised_training_eligible: bool
    generator_version: str
    scenario_variant: str | None = None
    campaign_stage: CampaignStage | None = None
